a.out: main.o SpaceTAXI.o  User.o  Recorder.o Driver_Recorder.o Trip.o Time.o Galaxy.o
	g++ main.o SpaceTAXI.o  User.o Recorder.o Driver_Recorder.o Trip.o Time.o Galaxy.o
main.o: main.cpp
	g++ -c main.cpp
SpaceTAXI.o: SpaceTAXI.cpp
	g++ -c SpaceTAXI.cpp
User.o: User.cpp
	g++ -c  User.cpp
Trip.o: Trip.cpp
	g++ -c  Trip.cpp	
Recorder.o: Recorder.cpp
	g++ -c  Recorder.cpp
Driver_Recorder.o: Driver_Recorder.cpp
	g++ -c  Driver_Recorder.cpp
Time.o: Time.cpp
	g++ -c  Time.cpp
Galaxy.o: Galaxy.cpp
	g++ -c Galaxy.cpp